### ISSUE TITLE
It doesn't generate class, it only generate interface (class diagram)

### ISSUE THREAD

**Issue by tempegarit** [Qwin/staruml-typescript#1]
Hi! Thanks for making this awesome extension. Unfortunately, i can't generate code from class. It only generate code from interface. Would you fix this? Thanks.

**Comment by Qwin** [comment]
Hmm weird it should have, ill check it out. Thanks for letting me know.

**Comment by Qwin** [comment]
I checked it and just created a quick class :

/**
 * 
 */
class Class1 {

    /**
     * 
     */
    public constructor() {
    }

    /**
     * 
     */
    Attribute1: String;
    /**
     * 
     */
    Attribute2: String;
}

Generates just fine. Can you send me your model (or create a simple one that doesn't work for you ).

**Comment by Qwin** [comment]
Closing this issue as its non reproducible, please feel free to create a new issue if you are still experiencing issues.
